name: 🚀 Planta Fácil CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: 📥 Checkout código
        uses: actions/checkout@v4

      - name: 🔧 Instala dependências (Frontend)
        run: npm install

      - name: 🧪 Build do Frontend
        run: npm run build

      - name: 📤 Deploy para Vercel (Frontend)
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: frontend
